version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: 'amannn/action-semantic-pull-request'
        update-types: [ "version-update:semver-patch" ]
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
