
name: PR Lint
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    paths:
      - "**/*.tf"
      - "**/*.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
