
name: PR Lint
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    paths:
      - "**/*.tf"
      - "**/*.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
