name: Release

permissions:
  contents: write
  issues: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    name: Release

    steps:
      - name: Checkout sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Create new release
        id: release
        uses: cycjimmy/semantic-release-action@1989a0fefc4aea321e07f717680ed8e345925dc1 # v7.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
